"use client";
import Link from"next/link";import{useEffect,useState}from"react";
const features=[["🗓️","Roadmap","AI-planned day-by-day study schedule.","/roadmap"],["🃏","Flashcards","Turn your PDF into interactive cards.","/flashcards"],["📝","MCQ / Quiz","Generate topic-based practice questions.","/quiz"],["🧠","Doubt Solver","Upload a question photo and get steps.","/doubt"],["📚","Notes Maker","Create structured exam-ready notes.","/notes"],["📄","PDF Compressor","Quickly open your external compressor.","/compressor"]];
export default function Home(){const[sc,setSc]=useState(false);
useEffect(()=>{const f=()=>setSc(scrollY>20);const move=e=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px")};addEventListener("scroll",f,{passive:true});addEventListener("pointermove",move,{passive:true});return()=>{removeEventListener("scroll",f);removeEventListener("pointermove",move)}},[]);
return <main><div className="blobs"><i/><i/><i/></div><div className="grid-glow"/><div className="cursor-glow"/>
<nav className={sc?"nav sc":"nav"}><Link className="logo" href="/">RX<span>Study</span></Link><div className="navlinks">{features.map(f=><Link key={f[1]} href={f[3]}>{f[1]}</Link>)}</div><Link className="navcta" href="/roadmap">Start Learning <b>↗</b></Link></nav>
<section className="hero"><div className="hero-orbit orbit1"/><div className="hero-orbit orbit2"/><div className="hero-badge"><i/> AI POWERED <span>•</span> STUDENT FIRST</div><h1>Study Smarter.<br/><span>Learn Faster.</span></h1><p>Your AI-powered study companion for roadmaps, flashcards, quizzes, notes and doubts.</p><div className="hero-actions"><Link className="btn btn-main" href="/roadmap"><span>Start Learning</span><b>↗</b></Link><a className="btn ghost" href="#features">Explore Features <b>↓</b></a></div>
<div className="float-card fc1"><em>✦</em><span>AI Doubt Solver</span><small>Step-by-step help</small></div><div className="float-card fc2"><em>✓</em><span>92% Quiz Score</span><small>Keep improving</small></div><div className="float-card fc3"><em>✎</em><span>Smart Notes</span><small>Exam ready</small></div>
<div className="hero-scroll"><span>SCROLL TO EXPLORE</span><i/></div></section>
<section id="features" className="section"><div className="section-head"><span>Everything in one place</span><h2>Tools built for <b>serious study.</b></h2><p>One focused workspace for planning, practice and revision.</p></div><div className="feature-grid">{features.map((f,i)=><Link className="feature" style={{"--delay":i*70+"ms"}} href={f[3]} key={f[1]}><div className="feature-top"><div className="icon">{f[0]}</div><span className="feature-num">0{i+1}</span></div><h3>{f[1]}</h3><p>{f[2]}</p><span className="arrow">Explore <b>↗</b></span></Link>)}</div></section>
<footer><div className="footer-line"/><span>Study smarter, every day.</span><b>Created by Ravi</b></footer></main>}