export const runtime="nodejs";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const MODELS=(process.env.GEMINI_MODELS||"gemini-3.5-flash,gemini-3.5-flash-lite").split(",").map(x=>x.trim()).filter(Boolean);
const MAX=4.3*1024*1024;
const b64=s=>{const m=typeof s==="string"&&s.match(/^data:(.*?);base64,(.*)$/s);return m?{mime:m[1],data:m[2]}:{mime:"application/pdf",data:s||""}};
async function ai(parts,json){let last="AI Response Error",status=0;for(const model of MODELS){for(let a=0;a<2;a++){try{const body={contents:[{parts}]};if(json)body.generationConfig={responseMimeType:"application/json"};const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+model+":generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":process.env.GEMINI_API_KEY},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json().catch(()=>({}));if(r.ok){const text=(d?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||"").join("");if(text)return{text};last="Empty AI response";break}status=r.status;last=d?.error?.message||("Status "+r.status);if(![429,500,503].includes(r.status))break}catch(e){last=e.message||"Server error"}await sleep(1000)}}return{error:"AI Error: "+last+(status===401||status===403?" Please check GEMINI_API_KEY.":"")}};
const arr=t=>{const c=t.replace(/\`\`\`json|\`\`\`/g,"").trim();try{return JSON.parse(c)}catch{const s=c.indexOf("[");const e=c.lastIndexOf("]");if(s<0||e<0)throw Error("No JSON");return JSON.parse(c.slice(s,e+1))}};
export async function POST(req){if(!process.env.GEMINI_API_KEY)return Response.json({error:"GEMINI_API_KEY missing. Add it in Vercel Environment Variables."},{status:500});try{const b=await req.json();
if(b.mode==="roadmap"){const subs=(b.subjects||[]).map(x=>"- "+x.name+": "+x.chapters+" Chapters").join("\n");const p=`Tum expert study planner ho. Student: ${b.name}. Exam days: ${b.days}. Daily hours: ${b.hours}. Subjects:\n${subs}\n\nHinglish me day-wise practical study roadmap banao. Chapter names invent mat karo; only Chapter 1, Chapter 2... use karo. Har day: Subject, Chapter, Study Time, Practice, Revision. Weekly revision, mock tests, breaks aur final revision include karo. Plain headings, no markdown table.`;return Response.json(await ai([{text:p}],false))}
if(b.mode==="flashcards"||b.mode==="quiz"){if(!b.pdf||b.pdf.length>MAX)return Response.json({error:"PDF missing or larger than 3 MB."},{status:413});const p=b64(b.pdf);const prompt=b.mode==="flashcards"?`PDF ke actual content se exactly ${b.count} useful flashcards banao. Language ${b.lang}. Content ke bahar mat jao. JSON only: [{"q":"Question","a":"Answer"}]`:`PDF ke actual content se exactly ${b.count} MCQs banao. Language ${b.lang}. Exactly 4 plausible related options, exactly 1 correct. JSON only: [{"q":"Question","o":["A","B","C","D"],"a":0,"why":"Short explanation"}]`;const o=await ai([{text:prompt},{inline_data:{mime_type:p.mime,data:p.data}}],true);if(o.error)return Response.json(o,{status:500});try{return Response.json(b.mode==="flashcards"?{cards:arr(o.text)}:{quiz:arr(o.text)})}catch{return Response.json({error:"AI JSON format error. Please try again."},{status:500})}}
if(b.mode==="doubt"){if(!b.image||b.image.length>MAX)return Response.json({error:"Image missing or too large."},{status:413});const p=b64(b.image);const prompt=`Subject: ${b.subject}. Answer language: ${b.lang}. Read this question image. Give Question, Understanding, Step-by-step Solution, Explanation and Final Answer. Student-friendly.`;return Response.json(await ai([{text:prompt},{inline_data:{mime_type:p.mime,data:p.data}}],false))}
if(b.mode==="notes"){if(!b.topic||!b.subject)return Response.json({error:"Subject and Topic are required."},{status:400});const p=`Class ${b.className}, Board ${b.board==="State Board"?b.stateBoard:b.board}, Subject ${b.subject}, Topic ${b.topic}, Type ${b.type}. Generate structured exam-focused notes with headings, bullets, definitions, important points, examples and formulas where relevant. Short Notes concise, Long Notes detailed. No giant paragraph.`;return Response.json(await ai([{text:p}],false))}
return Response.json({error:"Invalid request"},{status:400})}catch(e){return Response.json({error:"Server Error: "+(e.message||"Unknown")},{status:500})}}